name: Despliegue aplicacion Nodejs en Azure Web App

run-name: Configuracion para React y Vite ⚡

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: nodejs-devops
  AZURE_WEBAPP_PACKAGE_PATH: './client'
  NODE_VERSION: '18.x'
  
permissions:
  contents: read
  
jobs:
  Configuracion-inicial:
    runs-on: windows-latest
    steps:
      - name: Descarga el repositorio
        uses: actions/checkout@v3
  
      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
  
      - name: Instala las dependencias
        run: npm ci
        working-directory: ./client

      - name: Compila el proyecto
        run: npm run build --if-present
        working-directory: ./client

      - name: Ejecuta los tests
        run: npm run test:unit --if-present
        working-directory: ./client

      - name: Sube artefactos para tareas de despliegue
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
  
  Despliegue-en-Azure:
    runs-on: windows-latest
    needs: Configuracion-inicial

    environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
    steps:
      - name: Descarga los artefactos de la configuracion inicial
        uses: actions/download-artifact@v3
        with:
          name: node-app
  
      - name: 'Despliega en Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  